version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test
    ports:
      # стоит локальный postgres, поэтому стандартный порт занят
      - 5433:5432
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./scripts:/docker-entrypoint-initdb.d/"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    restart: always
    build: ./app/


